### ISSUE TITLE
0.8.0 finds non-existing issues of translation functions using variables.

### ISSUE THREAD

**Issue by MartijnR** [i18next/i18next-parser#41]
E.g. in this string

> // TODO would be good to not include nodes that weren't in the defaults parameter

The function added to index.js in [this commit](https://github.com/i18next/i18next-parser/commit/4985f4249306cce2253a01ab020ac298a80abf04) finds a match and outputs an "i18next-parser does not support variables in translation functions" error.

match[1] is `"t in the defaults parameter"`

**Comment by mogelbrod** [comment]
Having the same problem, possible fix:
```js
// From:
var noStringLiteralPattern = '[^a-zA-Z0-9_]((?:'+fnPattern+')(?:\\(|\\s)\\s*(?:[^\'"`\)]+\\)))';
// To:
var noStringLiteralPattern = '[^a-zA-Z0-9_]((?:'+fnPattern+')\s*\(\s*[^'"`)]+\))';
```

Changed regex requires the function name to be followed by parentheses, optionally prefixed by whitespace.

**Comment by karellm** [comment]
I have published `0.8.1` with a fix. Let me know if it got you covered. If not, please share any other string causing the issue.

@mogelbrod I have excluded any quote (single, double, back-tic) from the authorized characters before the `fnPattern`.

**Comment by MartijnR** [comment]
Thanks. The next false error I'm encountering is with this:

```
t = function( key, options ) {
   ....
}
```

matches[1] is "_t = function( key, options ))_"

Maybe this question doesn't belong in this issue, but would a warning (instead of a terminating error) perhaps be better for the use of variables? I use them a few times, for good reasons, and now I'll have to create copies of t, to allow i18next-parser to run. It just seems a little messy.

**Comment by wong2** [comment]
I'm still having this issue after upgrade to 0.8.1, the string is similar with @MartijnR

**Comment by wong2** [comment]
@karellm please have another look

**Comment by mogelbrod** [comment]
@karellm: I suggest using a stricter regex that only considers function call-like strings using parentheses to avoid false positives. Since it's meant to catch function calls it easier to look for function calling syntax (parentheses) rather than relying on a more liberal approach and then having to manually think of any exclusions.

**Comment by karellm** [comment]
@wong2 @mogelbrod  I just published `0.8.2`.

I followed your suggestion and removed tests for string literal without a parenthesis.

**Comment by wong2** [comment]
@karellm it works now, thanks a lot!

**Comment by MartijnR** [comment]
Thanks for adding the ignoreVariables option!
