### ISSUE TITLE
Key extraction to wrong namespace

### ISSUE THREAD

**Issue by tylerrasor** [i18next/i18next-parser#494]
## 🐛 Bug Report

When using the `useTranslation` hook to get two different TFunctions scoped to different namespaces, extraction should place keys into the namespace of the corresponding TFunction.

## To Reproduce

```js
const { t } = useTranslation();
const { t: otherT } = useTranslations('otherNs');
const header = t('header string');
const otherHeader = otherT('other string that should not be extracted');
```

## Expected behavior

Should get extracted to the default namespace:
```js
// translation.json
"header string": "header string"
```

But gets extracted to the namespace provided to the other `useTranslation` hook:
```js
// otherNs.json
"header string": "header string"
```

____

I believe this is the corresponding test that should be added, but haven't gotten much farther than that
```js
// javascript-lexer.test.js
it('uses default namespace when other t function', () => {
    const Lexer = new JavascriptLexer()
    const content =
      'const {t} = useTranslation("baz");' +
      'const {t:otherT} = useTranslation("otherNs");' +
      't("bar");'
    assert.deepEqual(Lexer.extract(content), [
      { namespace: 'baz', key: 'bar', ns: 'baz' },
    ])
  })
```

![image](https://user-images.githubusercontent.com/4198251/147149311-f3916725-a635-4b66-96fa-233b71bf4392.png)

## Your Environment

- *runtime version*: node v14
- *i18next version*: 21.5.2
- *i18next-parser version*: 5.3.0
- *os*: Mac
- *any other relevant information*

**Comment by karellm** [comment]
@tylerrasor It is indeed a missing feature at the moment.

**Comment by tux21b** [comment]
I just discovered the same bug with key prefixes instead of namespaces. Looks like i18next-parser threads all t functions with the config that appeared last.

```
const { t: tRoot } = useTranslation();
const { t } = useTranslation('translation', {keyPrefix: 'staticData.locations'});
```

**Comment by cah4a** [comment]
any progress here?

**Comment by Bladieblah** [comment]
Bump

**Comment by thomasmery** [comment]
Hi there,

Got bit by this again today ...

unfortunately can't volunteer for a PR

but would really love to see this solved

thanks

**Comment by karellm** [comment]
Should be fixed with #1083. Deployed as `9.3.0`

**Comment by Pouet--** [comment]
@karellm Thanks a lot ! It there a way to upgrade to this version right now ?

**Comment by Pouet--** [comment]
It still does not work for keyPrefix with version 9.3.0.
I quote @tux21b "Looks like i18next-parser threads all t functions with the config that appeared last."
