### ISSUE TITLE
Incorrect extraction for multiple `useTranslation` on the same page

### ISSUE THREAD

**Issue by affanshahid** [i18next/i18next-parser#973]
## 🐛 Bug Report

If I have multiple invocations of `useTranslation` using different namespaces on the same page, the extraction does not work correctly.

## To Reproduce
Create a component like:

```tsx
const useSchema = () => {
  const { t } = useTranslation('validation');
  t('errors.invalid_type_received_undefined') // Note: `errors.invalid_type_received_undefined` is in ns validation
  // ...
};



export const HomePlanStep = () => {
  const { t } = useTranslation(['application-address', 'common']);
  useSchema()

  return <p>{t('homePlanStep.submitBtnText')}</p> // Note: this is in ns application-address
};
```

The dictionary that gets generated incorrectly has `errors.invalid_type_received_undefined` associated with NS: 'application-address'. The actual app runs just fine like this, only the extraction generates incorrect dictionaries.

If I make the following change, the dictionary gets generated correctly:
```tsx
const useSchema = () => {
  const { t } = useTranslation('validation');
  t('errors.invalid_type_received_undefined', { ns: 'validation' }) // Note: added explicit ns
  // ...
};
```
Now the dictionary does not associate `errors.invalid_type_received_undefined` with NS: 'application-address'.

## Expected behavior

The extractor should not mix-up namespaces when extracting

## Your Environment

- *runtime version*: Node v18.19.0
- *i18next version*: v23.7.16
- *i18next-parser version*: v8.12.0
- *os*: MacOS Sonoma 14.2.1

**Comment by karellm** [comment]
Should be fixed with #1083. Deployed as `9.3.0`

**Comment by Pouet--** [comment]
It still does not work for different keyPrefix values. I made a post on the PR [here](https://github.com/i18next/i18next-parser/pull/1083#issuecomment-2685101123)

**Comment by rocky-luo-opus** [comment]
It doesn't work, see [1137](https://github.com/i18next/i18next-parser/issues/1137)
